kwords={
    "cristi": "cristi, adica cel mai tare?",
    "ok": "ok, mai bine doua chei",
    "dezintegrez": "dezintegrez, bine ca nu dez-char-egrez",
    "critica": "critica, bine ca nu patrunzatoare",
    "interesant": "interesant, bine ca nu char-eresant",
    "handicapat": "handicapat, bine ca nu leg-icapat",
    "lasama in pace": "bine ca nu lasa-ma in razboi",
    "lasa-ma in pace": "bine ca nu lasa-ma in razboi",
    "pascal": "pas-cal, bine ca nu pas-iapa",
    "cacat": "ca-cat, bine ca nu ca-dog",
    "ne pasa": "ne pasa, bine ca nu ne sut",
    "pasa": "pasa, bine ca nu sut",
    "albert": "albert, bine ca nu rosu-bert",
    "cringe": "crin-ge, bine ca nu lalea-ge",
}